
text1 = "THE THING THAT YOU SEE IS CALLED TRAMPOLINE";
text2 = "BY JUMPING ON IT YOUR JUMP SPEED WILL INCREASE!";
text3 = "TRY GET ALL THE COINS BY JUMPING ON TRAMPOLINE";

text_speed = 0.5;
char = 0;
draw_set_font(fontTutorial);