

text1 = "CREATURES IN THIS GAME IS HARMFUL, LIKE THIS MUSHROOM!";
text2 = "DIRECT CONTACT TO THEM WILL DECREASE YOUR HEART!";
text3 = "IF YOUR HEARTS RUNS OUT, YOUR GAME TRIALS WILL ALSO DECREASED BY ONE!";
text4 = "IF THE GAME TRIALS RUNS OUT, THE GAME WILL BE OVER!";

text_speed = 0.5;
char = 0;
draw_set_font(fontTutorial);