key = 0;
left = true;
right = true;

text1 = "CREATURES IN THIS GAME IF HARMFUL, LIKE THIS MUSHROOM!";
text2 = "AVOID DIRECT CONTACT WITH THEM OR YOUR HEART WILL BE REDUCED BY ONE EACH TIME YOU COLLIDE WITH ONE OF THEM";
text3 = "IF YOUR HEARTS RUNS OUT YOUR GAME TRIALS ALSO DECREASED BY ONE";

text_speed = 0.5;
char = 0;
draw_set_font(fontTutorial);